"""Extracting something runnable from a bug report.

Stage 1 of reproduction needs one thing: an expression to execute. Reports carry
it in one of three forms, and all three are extracted deterministically. A model
is not asked, because a model asked for "the code that crashed" will happily
invent a plausible call that never appeared in the report, and stage 1 exists
precisely to find out whether the reported input really crashes.

When nothing runnable can be found, the honest answer is to ask the reporter,
which is what `CLARIFY` is for.
"""

from __future__ import annotations

import ast
import re
from dataclasses import dataclass

#: A fenced block, optionally tagged as Python.
FENCE_PATTERN = re.compile(r"```(?:py|python)?\s*\n(.*?)```", re.DOTALL)

#: The call line under a traceback frame, indented beneath `File "...", line N`.
TRACEBACK_CALL_PATTERN = re.compile(
    r'File "(?P<file>[^"]+)", line \d+, in (?P<scope>\S+)\n\s+(?P<call>.+)'
)

#: An inline call written in prose, for example ``parse_date("2024-13-01")``.
INLINE_CALL_PATTERN = re.compile(r"\b([a-z_][a-z0-9_]*)\s*\(([^()\n]{0,200})\)", re.IGNORECASE)

#: Frames belonging to the reporter rather than the library.
CALLER_SCOPES = frozenset({"<module>", "<stdin>", "main"})


@dataclass(frozen=True, slots=True)
class ReproInput:
    """Something runnable, and where it came from."""

    code: str
    origin: str
    symbol: str | None = None

    @property
    def is_expression(self) -> bool:
        """Whether the code is a single expression rather than a block."""
        return "\n" not in self.code.strip()


def parses(code: str) -> bool:
    """Return whether a snippet is syntactically valid Python."""
    try:
        ast.parse(code)
    except SyntaxError:
        return False
    return True


def called_symbol(code: str) -> str | None:
    """Return the name of the outermost function called in a snippet."""
    try:
        tree = ast.parse(code)
    except SyntaxError:
        return None
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Name):
                return node.func.id
            if isinstance(node.func, ast.Attribute):
                return node.func.attr
    return None


def from_report(text: str) -> ReproInput | None:
    """Find something runnable in a report, or return None.

    Preference order reflects how much the reporter actually committed to:
    a fenced block is what they ran, a traceback call line is what their
    interpreter ran, and an inline call is a description of what they ran.
    """
    for block in FENCE_PATTERN.findall(text):
        candidate = _strip_prompts(block)
        if candidate and parses(candidate) and "def " not in candidate.split("\n")[0]:
            return ReproInput(
                code=candidate.strip(), origin="fenced_block", symbol=called_symbol(candidate)
            )

    for match in TRACEBACK_CALL_PATTERN.finditer(text):
        if match.group("scope") not in CALLER_SCOPES:
            continue
        call = match.group("call").strip()
        if parses(call) and "(" in call:
            return ReproInput(code=call, origin="traceback_call", symbol=called_symbol(call))

    for match in INLINE_CALL_PATTERN.finditer(text):
        call = match.group(0)
        # Prose mentions functions without arguments constantly ("parse_date()
        # is broken"). Only a call carrying an argument is evidence of input.
        if match.group(2).strip() and parses(call):
            return ReproInput(code=call, origin="inline_call", symbol=match.group(1))

    return None


def build_script(repro: ReproInput, *, package: str) -> str:
    """Wrap a snippet in a runnable script.

    The script imports the package under test and nothing else, and prints
    nothing on success, so the sandbox exit code alone distinguishes "reproduced"
    from "did not reproduce".
    """
    lines = [
        "# Generated by ProofPR stage 1 reproduction. Runs the reported input verbatim.",
        "import sys",
        "",
        "# The worktree is a checkout, not an installed package, so the usual source",
        "# roots are added explicitly. Without this a src-layout project fails with",
        "# ModuleNotFoundError and stage 1 would call a real bug an environment problem.",
        'for _root in ("src", "."):',
        "    if _root not in sys.path:",
        "        sys.path.insert(0, _root)",
        "",
    ]
    # Several flat modules are imported in configuration order, so a symbol the
    # report names bare resolves to whichever module defines it.
    for name in [part.strip() for part in package.split(",") if part.strip()]:
        lines.append(f"import {name}")
        lines.append(f"from {name} import *  # noqa: F403 - the report names a bare symbol")
    lines.append("")
    if repro.is_expression:
        lines.append(f"result = {repro.code}")
        lines.append('print("no exception, result was:", result, file=sys.stderr)')
    else:
        lines.append(repro.code)
        lines.append('print("no exception raised", file=sys.stderr)')
    return "\n".join(lines) + "\n"


def _strip_prompts(block: str) -> str:
    """Remove shell and REPL prompts from a pasted block."""
    lines = []
    for raw in block.splitlines():
        line = raw.rstrip()
        if line.startswith(("$ ", "% ")):
            continue
        if line.startswith((">>> ", "... ")):
            line = line[4:]
        lines.append(line)
    return "\n".join(lines).strip()
